In [41]:
import pandas as pd

# Excel dosyasını oku
df_1 = pd.read_excel('cancer-DisGeNET.xlsx')


# DataFrame'i görüntüle
print(df_1)

       geneSymbol                          diseaseName
0            A1BG                         Glioblastoma
1            A1BG                           Meningioma
2            A1BG  Subependymal Giant Cell Astrocytoma
3            A1BG               Hepatocellular Adenoma
4            A1BG             Angiomyolipoma of kidney
...           ...                                  ...
329928   LNC-LBCS   Hormone refractory prostate cancer
329929   MIR223HG                             leukemia
329930   MIR223HG          Leukemia, Myelocytic, Acute
329931   MIR223HG                       Leukemogenesis
329932   MIR223HG                   Childhood Leukemia

[329933 rows x 2 columns]

In [42]:
birlesik_df_1 = pd.concat([df_1['diseaseName'], df_1['geneSymbol']], axis=1)
birlesik_df_1

                                diseaseName geneSymbol
0                              Glioblastoma       A1BG
1                                Meningioma       A1BG
2       Subependymal Giant Cell Astrocytoma       A1BG
3                    Hepatocellular Adenoma       A1BG
4                  Angiomyolipoma of kidney       A1BG
...                                     ...        ...
329928   Hormone refractory prostate cancer   LNC-LBCS
329929                             leukemia   MIR223HG
329930          Leukemia, Myelocytic, Acute   MIR223HG
329931                       Leukemogenesis   MIR223HG
329932                   Childhood Leukemia   MIR223HG

[329933 rows x 2 columns]

In [43]:
df_yeni = pd.DataFrame(birlesik_df_1)
df_grouped = df_yeni.groupby('diseaseName')['geneSymbol'].apply(', '.join).reset_index()
df_grouped #geneSymbol

,diseaseName,geneSymbol
0,ACTH-Secreting Pituitary Adenoma,"NR0B1, CCND1, BMP4, BRAF, CDH1, CDK3, CDKN1A, ..."
1,"ADENOCARCINOMA, COLONIC, SOMATIC",RAD54L
2,"ADRENOCORTICAL CARCINOMA, HEREDITARY","EGFR, GJA8, GSTM1, GSTP1, GSTT1, IFNG, KRT7, K..."
3,"ADRENOCORTICAL TUMOR, SOMATIC","GNAI2, PRKAR1A"
4,AIDS with Kaposi's sarcoma,"AMCN, ANGPT1, BCKDHB, BCL2, CD34, CX3CR1, FGF2..."
...,...,...
3924,thyroid cancer lymphoma,MIR146B
3925,tubular adenomas and adenocarcinomas,"CDKN2A, MLH1"
3926,tumor miofibroblÃ¡stico peribronquial congÃ©nito,"CD6, ETV6, NTRK3"
3927,type B thymoma,"TTR, CD274"
3928,upper GI cancer,"ERBB2, XRCC1"

In [25]:
df_2 = pd.read_excel('miRtarBase_homoSapian.xlsx')

miRNA = df_2['miRNA']
Target_Gene = df_2['Target Gene']

birlesik_df_2 = pd.concat([df_2['miRNA'], df_2['Target Gene']], axis=1)
birlesik_df_2

                  miRNA Target Gene
0        hsa-miR-20a-5p       HIF1A
1        hsa-miR-20a-5p       HIF1A
2        hsa-miR-20a-5p       HIF1A
3       hsa-miR-146a-5p       CXCR4
4       hsa-miR-146a-5p       CXCR4
...                 ...         ...
502647      hsa-miR-943       TULP4
502648    hsa-miR-96-5p      PFKFB3
502649    hsa-miR-96-5p        RGS2
502650   hsa-miR-99a-5p       IFIT3
502651   hsa-miR-99b-5p       IFIT3

[502652 rows x 2 columns]

In [27]:
df_yeni_2 = pd.DataFrame(birlesik_df_2)
df_grouped_2 = df_yeni_2.groupby('miRNA')['Target Gene'].apply(', '.join).reset_index()

In [35]:
df_GO_MF = pd.read_excel('GO_MF.xlsx')
df_GO_BP = pd.read_excel('GO_BP.xlsx')
df_GO_CC = pd.read_excel('GO_CC.xlsx')
secilen_df_go = pd.concat([df_GO_CC, df_GO_BP, df_GO_MF], ignore_index=True, axis = 0)
secilen_df_go

,GO_Term,Gene_Name
0,GOCC_90S_PRERIBOSOME,"BMS1,BOP1,ENSG00000275464,HEATR1,IMP3,IMP4,KRI..."
1,GOCC_9PLUS0_MOTILE_CILIUM,"CFAP45,DNAH11,DNAH5,ENKUR,ODAD4 ..."
2,GOCC_9PLUS0_NON_MOTILE_CILIUM,"ABCA4,ARL3,ARR3,ATP1A4,BBS4,BBS7,BSG,C1orf115,..."
3,GOCC_9PLUS2_MOTILE_CILIUM,"ABHD2,ACE,AK1,AK2,AK8,AKAP3,AKAP4,ATG16L1,ATP1..."
4,GOCC_ACETYLCHOLINE_GATED_CHANNEL_COMPLEX,"CHRFAM7A,CHRNA1,CHRNA2,CHRNA3,CHRNA4,CHRNA5,CH..."
...,...,...
10456,GOMF_WW_DOMAIN_BINDING,"CDC25C,DAZAP2,ENAH,ENTREP3,KIF20B,LITAF,NDFIP1..."
10457,GOMF_XENOBIOTIC_TRANSMEMBRANE_TRANSPORTER_ACTI...,"ABCA3,ABCA8,ABCB1,ABCB11,ABCB5,ABCC1,ABCC10,AB..."
10458,GOMF_XMP_5_NUCLEOSIDASE_ACTIVITY,"ACP3,NT5C1A,NT5C1B,NT5C2,NT5C3A,NT5E ..."
10459,GOMF_ZINC_ION_BINDING,"AARS1,AARS2,ACE,ACE2,ACER3,ACMSD,ACR,ADA,ADA2,..."
10460,GOMF_ZINC_ION_TRANSMEMBRANE_TRANSPORTER_ACTIVITY,"SLC30A1,SLC30A10,SLC30A2,SLC30A3,SLC30A4,SLC30..."

In [47]:
df_grouped.columns = [0, 1]  # Sütun isimlerini sıfırla
df_grouped_2.columns = [0, 1]  # Sütun isimlerini sıfırla
secilen_df_go.columns = [0, 1]  # Sütun isimlerini sıfırla
secilen_df = pd.concat([df_grouped, df_grouped_2,secilen_df_go], ignore_index=True, axis = 0)
secilen_df

,0,1
0,ACTH-Secreting Pituitary Adenoma,"NR0B1, CCND1, BMP4, BRAF, CDH1, CDK3, CDKN1A, ..."
1,"ADENOCARCINOMA, COLONIC, SOMATIC",RAD54L
2,"ADRENOCORTICAL CARCINOMA, HEREDITARY","EGFR, GJA8, GSTM1, GSTP1, GSTT1, IFNG, KRT7, K..."
3,"ADRENOCORTICAL TUMOR, SOMATIC","GNAI2, PRKAR1A"
4,AIDS with Kaposi's sarcoma,"AMCN, ANGPT1, BCKDHB, BCL2, CD34, CX3CR1, FGF2..."
...,...,...
16984,GOMF_WW_DOMAIN_BINDING,"CDC25C,DAZAP2,ENAH,ENTREP3,KIF20B,LITAF,NDFIP1..."
16985,GOMF_XENOBIOTIC_TRANSMEMBRANE_TRANSPORTER_ACTI...,"ABCA3,ABCA8,ABCB1,ABCB11,ABCB5,ABCC1,ABCC10,AB..."
16986,GOMF_XMP_5_NUCLEOSIDASE_ACTIVITY,"ACP3,NT5C1A,NT5C1B,NT5C2,NT5C3A,NT5E ..."
16987,GOMF_ZINC_ION_BINDING,"AARS1,AARS2,ACE,ACE2,ACER3,ACMSD,ACR,ADA,ADA2,..."
16988,GOMF_ZINC_ION_TRANSMEMBRANE_TRANSPORTER_ACTIVITY,"SLC30A1,SLC30A10,SLC30A2,SLC30A3,SLC30A4,SLC30..."

In [48]:
#secilen_df.to_excel('new_domain_knowledge_mirna_disease_go.xlsx', index=False)
secilen_df.to_csv('birlesik_dosya_all.csv', index=False)
#df_grouped.to_csv('birlesik_dosya_disease.csv', index=False)
#df_grouped.to_excel('new_domain_knowledge_disease_2.xlsx', index=False)
#df_grouped.columns = [0, 1]  # Sütun isimlerini sıfırla